### ISSUE TITLE
sorry, wrong repo.

### ISSUE THREAD

**Issue by lanx-x** [bsansouci/showdown-ghost#1]
sorry, wrong repo.

**Comment by bsansouci** [comment]
No problem :)

**Comment by lanx-x** [comment]
Hi, @bsansouci . Do you use this repo in your ghost blog?

I met some bug when use the official ghost: https://github.com/TryGhost/Ghost/issues/5632 .

Actually, the bug was fixed in latest version of showdown, so, Is there any possible to  you to update your repo to latest showdown?
